# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pubtime']},
        ),
    ]
